### PR TITLE
Added prerelease note.

### PR DESCRIPTION
**Pull request by RaoHammas**
Package is still a prerelease/preview so have added a note about it, to enable prerelease in nuget tool before trying to find it, in package manager. And added link to nuget package.

### CODE REVIEW

**Comment by michael-hawker** [comment]
Thanks @RaoHammas, I think this link was a placeholder for an image that's in the main [docs repo](https://github.com/MicrosoftDocs/WindowsCommunityToolkitDocs) for when this content moves there, eh @Sergio0694?

**Comment by Sergio0694** [comment]
@michael-hawker Yeah uh... That link was probably just a placeholder.
I think the idea was to have an `<a href/>` node eventually, with the NuGet logo and then a download link to it.
I'd say we should decide whether to just have the link as an hyperlink, or as an image, and update that accordingly. The changes in this PR are not correct either way, because right now it's using an inline image markdown node with no image, which results in a broken thumbnail. At least we should drop the leading `!` if we just want to use a normal text hyperlink 🙂

**Comment by michael-hawker** [comment]
@Sergio0694 let's close out the existing doc PRs here and then think about moving the content to the doc repo?

**Comment by michael-hawker** [comment]
These are for the final docs, so I don't think this makes sense right now (since we'll be pushing those up soon). We probably want to update the readme instead.

**Pull request closed without merging**
